steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.api', '-t', 'gcr.io/$PROJECT_ID/nofomo-api', '.']
  
  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nofomo-api']
  
  # Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nofomo-api'
      - '--image=gcr.io/$PROJECT_ID/nofomo-api'
      - '--region=asia-southeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'