FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o summarizer ./cmd/summarizer

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/summarizer .
CMD ["./summarizer"]